sudo: required

language: php
php: 7.2
env:
  global:
    - HELLO="world"
    - PATH="$TRAVIS_BUILD_DIR:$PATH"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - wget -qO ee https://rt.cx/ee4beta && sudo bash ee
  - sudo ee cli update --yes

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  #- sudo php easyengine.phar cli info
