sudo: required

language: php
php: 7.2

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install php7.2-cli
  - /usr/bin/php7.2 -v
  - ls -al
  - pwd
  - git clone https://github.com/EasyEngine/easyengine.git
  - ls -al
  - cp prepare.sh easyengine/
  - cp deploy.sh easyengine/
  - cd easyengine
  - ls -al
  - composer install --no-interaction
  
before_script:
- ./prepare.sh


cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  #- sudo php easyengine.phar cli info
