sudo: required

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install php7.2-cli
  - php -v
  - sudo update-alternatives --set php /usr/bin/php7.2

before_script:
  - php -v
  - git clone https://github.com/EasyEngine/easyengine.git
  - ls -al
  - cp prepare.sh easyengine/
  - cd easyengine
  - ls -al
  - composer install --no-interaction
  - php -dphar.readonly=0 ./utils/make-phar.php easyengine.phar --quite  > /dev/null
  - sudo ls
  - sudo php easyengine.phar cli info
