sudo: required

language: php
php: 7.1
env:
  global:
    - HELLO="world"
    - PATH="$TRAVIS_BUILD_DIR:$PATH"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - ls
  - composer update -vvv
  
before_script:
  - ls -al

script:
  - ls asdasd

after_script:
  - sudo ls

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  #- sudo php easyengine.phar cli info
