sudo: required

language: php
php: 7.1
env:
  global:
    - HELLO="world"
    - PATH="$TRAVIS_BUILD_DIR:$PATH"

install:
  - ls
  - /bin/bash -c 'curl -i -H "Authorization: $GITHUB_TOKEN" "https://api.github.com/repos/EasyEngine/easyengine/releases?per_page=1"
  
before_script:
  - ls -al

script:
  - ls asdasd

after_script:
  - sudo ls

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  #- sudo php easyengine.phar cli info
